[tool.poetry]
name = "hou-intern-23"
version = "0.1.0"
description = ""
authors = ["Wynn Boss <wynn.boss@bjss.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
